pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: 'https://github.com/YOUR_USERNAME/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                pip3 install --upgrade pip
                pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                pytest --junitxml=report.xml
                '''
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'report.xml', fingerprint: true
        }
    }
}
