#!/bin/bash

kubectl apply -f blue_deployment.yaml

kubectl rollout status deployment/messaging-blue

while true
do
  curl -s http://localhost:8000 > /dev/null
  sleep 1
done &

sleep 10
kill $!

kubectl get pods
